spring.application.name=springapp
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.name=springapp
info.app.description=this is my first spring app
info.app.version=1.0
info.app.myinfo=this some text